-- Table: public.temperatures

-- DROP TABLE public.temperatures;

CREATE TABLE public.temperatures
(
    dallastemp numeric(4,2),
    dhttemp numeric(4,2),
    dhthumi numeric(4,2),
    led_colour text[] COLLATE pg_catalog."default",
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "timestamp" timestamp(6) with time zone DEFAULT now(),
    CONSTRAINT temperatures_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.temperatures
    OWNER to postgres;
COMMENT ON TABLE public.temperatures
    IS 'Testiningingengs';

COMMENT ON COLUMN public.temperatures.dallastemp
    IS 'dallas anturille';

COMMENT ON COLUMN public.temperatures.dhttemp
    IS 'dht22 anturille';
-- Index: dallastemp_dhthumi

-- DROP INDEX public.dallastemp_dhthumi;

CREATE INDEX dallastemp_dhthumi
    ON public.temperatures USING btree
    (dallastemp DESC NULLS LAST)
    INCLUDE(dhthumi)
    TABLESPACE pg_default;
-- Index: dallastemp_dhttemp

-- DROP INDEX public.dallastemp_dhttemp;

CREATE INDEX dallastemp_dhttemp
    ON public.temperatures USING btree
    (dallastemp DESC NULLS LAST)
    INCLUDE(dhttemp)
    TABLESPACE pg_default;
-- Index: dallastempi

-- DROP INDEX public.dallastempi;

CREATE INDEX dallastempi
    ON public.temperatures USING btree
    (dallastemp DESC NULLS LAST)
    TABLESPACE pg_default;
-- Index: dhthumi_dallas

-- DROP INDEX public.dhthumi_dallas;

CREATE INDEX dhthumi_dallas
    ON public.temperatures USING btree
    (dhthumi DESC NULLS LAST)
    INCLUDE(dallastemp)
    TABLESPACE pg_default;
-- Index: dhthumi_dhttemp

-- DROP INDEX public.dhthumi_dhttemp;

CREATE INDEX dhthumi_dhttemp
    ON public.temperatures USING btree
    (dhthumi DESC NULLS LAST)
    INCLUDE(dhttemp)
    TABLESPACE pg_default;
-- Index: dhthumin

-- DROP INDEX public.dhthumin;

CREATE INDEX dhthumin
    ON public.temperatures USING btree
    (dhthumi DESC NULLS LAST)
    TABLESPACE pg_default;
-- Index: dhttemp_dallas

-- DROP INDEX public.dhttemp_dallas;

CREATE INDEX dhttemp_dallas
    ON public.temperatures USING btree
    (dhttemp DESC NULLS LAST)
    INCLUDE(dallastemp)
    TABLESPACE pg_default;
-- Index: dhttemp_dhthumi

-- DROP INDEX public.dhttemp_dhthumi;

CREATE INDEX dhttemp_dhthumi
    ON public.temperatures USING btree
    (dhttemp DESC NULLS LAST)
    INCLUDE(dhthumi)
    TABLESPACE pg_default;
-- Index: dhttempi

-- DROP INDEX public.dhttempi;

CREATE INDEX dhttempi
    ON public.temperatures USING btree
    (dhttemp DESC NULLS LAST)
    TABLESPACE pg_default;
-- Index: led_dallas_dhttemp

-- DROP INDEX public.led_dallas_dhttemp;

CREATE INDEX led_dallas_dhttemp
    ON public.temperatures USING btree
    (led_colour COLLATE pg_catalog."default" DESC NULLS LAST)
    INCLUDE(dallastemp, dhttemp)
    TABLESPACE pg_default;
-- Index: led_dallas_humi

-- DROP INDEX public.led_dallas_humi;

CREATE INDEX led_dallas_humi
    ON public.temperatures USING btree
    (led_colour COLLATE pg_catalog."default" ASC NULLS LAST)
    INCLUDE(dallastemp, dhthumi)
    TABLESPACE pg_default;
-- Index: led_dhttemp_dallas

-- DROP INDEX public.led_dhttemp_dallas;

CREATE INDEX led_dhttemp_dallas
    ON public.temperatures USING btree
    (led_colour COLLATE pg_catalog."default" ASC NULLS LAST)
    INCLUDE(dallastemp, dhttemp)
    TABLESPACE pg_default;
-- Index: led_humi_dallas

-- DROP INDEX public.led_humi_dallas;

CREATE INDEX led_humi_dallas
    ON public.temperatures USING btree
    (led_colour COLLATE pg_catalog."default" ASC NULLS LAST)
    INCLUDE(dallastemp, dhthumi)
    TABLESPACE pg_default;
-- Index: led_humi_dht

-- DROP INDEX public.led_humi_dht;

CREATE INDEX led_humi_dht
    ON public.temperatures USING btree
    (led_colour COLLATE pg_catalog."default" ASC NULLS LAST)
    INCLUDE(dhttemp, dhthumi)
    TABLESPACE pg_default;